config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    get :search, on: :collection
  end  
  resources :comments, only: %i[create]
  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  belongs_to :post
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  has_one_attached :image
  include PgSearch
  extend FriendlyId

  validates :title, :author, :body, presence: true
  has_many :comments, dependent: :destroy

  friendly_id :title, use: :slugged

  pg_search_scope :search,
                  against: %i[title author body],
                  associated_against: { comments: %i[body] } # inclui os comentarios na busca
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
       devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create!(comments_params)

    redirect_to comment.post, notice: 'O seu comentário foi enviado.'
  end

  private

  def comments_params
    params.require(:comment).permit(:post_id, :author, :body)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

def search
  @posts = Post.search(search_params[:q])
end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit; end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Artigo criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Artigo atualizado com sucesso.'}
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Artigo apagado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:title, :author, :body, :image)
  end

  def search_params
    params.permit(:q)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog de TI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="bg-primary text-white mb-4 p-3 text-center">
      <%= link_to root_path, class: 'text-white' do  %>
        <h1 class="display-4">Blog de T.I</h1>
      <% end %>
      <p class="lead">Olá, aqui você encontrará artigos sobre programação, tecnologia e carreira
      </p>
    </div>
    <div class="container">
      <% flash.each do |type, message| %>
        <div class="alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show" role="alert">
          <%= message %>
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      <% end %>
      <div class='row'>
        <div class='col-4 offset-8'>
          <div class='search'>
            <%= form_with url: search_posts_path, method: :get, local: true, class: 'form-inline' do |form| %>
              <div class='form-group mx-3 mb-3'>
                <%= form.search_field :q, class: 'form-control', required: true,
                  placeholder: 'Busca', value: params[:q] %>
              </div>
              <%= form.submit 'Buscar', class: 'btn btn-primary mb-3',
                data: { disable_with: 'Buscando...⌛' } %>
            <% end %>
          </div>
        </div>
      </div>
      <%= yield %>
    </div>
    <footer class="bg-primary text-white mt-4 p-4 text-center">
      Copyright &copy; Blog de T.I <%= Date.current.year %>.
      <div class="text-center mt-2">
        <% if signed_in? %>
          <%= link_to 'Sair', destroy_user_session_path, method: :delete, class:'btn btn-success' %>
        <% else %>
          <%= link_to 'Entrar', new_user_session_path, class:'btn btn-success' %>
        <% end %>
      </div>
    </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true, multipart: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :author%>
    <%= form.text_field :author, :value=>current_user.name, class: 'form-control', :readonly => true%>
  </div>
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 5 %>
  </div>
  <div class="form-group">
  <%= form.label :image %>
  <%= form.file_field :image, class: 'form-control' %>
</div>
  <div class="actions">
    <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Criando....⌛'}%>
    <%= link_to 'Cancelar', posts_path, class: 'btn btn-danger' %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="card bg-light mb-3">
  <div class="card-body post-show">
 
    <h3><%= link_to post.title, post, class:'text-dark' %></h3>
    <div class="text-muted mb-3">
    <%= image_tag post.image, class: 'img-fluid mb-3' %>
      <em>Autor: <%= post.author %> ( <%= l post.created_at, format: :long %> )</em>
    </div>
    <p>
      <%= post.body.truncate(400).gsub("\n", "<br>").html_safe %>
    </p>
    <p class="text-muted"><%= pluralize(post.comments.count, 'Comentário')%> </p>
    <%= link_to  "Ler Artigo", post, class:"btn btn-primary" %>
    <% if signed_in? %>
      <%= link_to  "Editar Artigo", edit_post_path(post), class:"btn btn-secondary" %>
      <%= link_to  "Apagar Artigo", post, method: :delete, class:"btn btn-danger",
        data: { confirm: 'Deseja apagar este artigo?'}%>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editando Artigo</h1>
<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render (post) %>
<% end %>
<hr>
<div class="text-right">
  <% if signed_in? %>
    <%= link_to 'Novo Post', new_post_path, class:'btn btn-success' %>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Novo Artigo</h1>
<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<h2 class="text-muted">
  <% if @posts.any? %>
    <%= pluralize(@posts.count, 'resultado') %> encontrados:
  <% else %>
    Nenhum resultado encontrado.
  <% end %>
</h2>
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/posts/show.html.erb
<div class="shadow p-3 mb-5 bg-light rounded post-show">
  <%= image_tag @post.image, class: 'img-fluid mb-3' %>
  <h2 class="text-dark text-center"><%= @post.title %></h2>
  <hr>
  <p class="p-3"><%= @post.body.gsub("\n", "<br>").html_safe %></p>
  <small>
    <p class="text-muted text-right"><em><strong>Por: <%= @post.author %> </strong><br>
        <%= l @post.created_at, format: :long %></em></p>
  </small>
  <%= link_to 'Voltar', posts_path, class: 'btn btn-primary mt-3' %>
</div>
<div class="m-5">
  <div class="text-center">
    <h4><%= pluralize(@post.comments.count, 'Comentário')%>
      <% if @post.comments.none? %>
        <span class="badge badge-success">Seja o primeiro a comentar!</span>
      <% end %>
    </h4>
  </div>
  <div class='shadow-sm m-3 p-3 bg-light rounded'>
    <%= form_with model: @comment, local: true do |form|  %>
      <%= form.hidden_field :post_id, value: @post.id %>
      <div class="form-group">
        <%= form.label :author %>
        <% if signed_in? %>
          <%= form.text_field :author, :value=>current_user.name, class: 'form-control', :readonly => true%>
        <% else %>
          <%= form.text_field :author, class: 'form-control'%>
        <% end %>
      </div>
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 5, required: true %>
      </div>
      <div class="actions">
        <%= form.submit class: 'btn btn-primary', data: { disable_with: 'Criando....⌛'}%>
        <%= link_to 'Cancelar', posts_path, class: 'btn btn-danger' %>
      </div>
    <% end %>
  </div>
  <% @comments.each do |comment| %>
    <div class='shadow-sm m-3 p-3 bg-light rounded'>
      <div class='row'>
        <div class='col'>
          <strong><%= comment.author %></strong>
        </div>
        <div class='col text-right'>
          <em data-toggle='tooltip' data-placement='top' title='<%= l comment.created_at, format: :long %>'>
            <%= time_ago_in_words comment.created_at %> atrás
          </em>
        </button>
      </div>
    </div>
    <hr>
    <%# ATENÇÃO: Sempre que usarmos \n (como na linha abaixo), precisamos usar áspas duplas %>
    <%= sanitize(comment.body.gsub("\n", '<br>')).html_safe %>
  </div>
<% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>